[package]
name = "elinvar"
version = "0.0.1"
authors = [
    "Graham Cox <graham@grahamcox.co.uk>",
    "Shane DeSeranno <tyren@syntheticstream.com>"
]

[lib]
name = "libelinvar"
path = "src/lib.rs"

[[bin]]
name = "elinvar"
path = "src/bin.rs"
